checks: Add retry logic to dotnet format style step as well
I can't imagine dotnet format whitespace ever segfaulting,
so hopefully it won't be needed there.

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -40,12 +40,22 @@ jobs:
         run: |
           dotnet format whitespace --verify-no-changes --report ./whitespace-report.json -v d
 
+      # For some unknown reason this step sometimes fails with exit code 139 (segfault?),
+      # so in that case we'll try again (3 tries max).
       - name: Run dotnet format style
         run: |
-          dotnet format style --severity info --verify-no-changes --report ./style-report.json -v d
+          attempt=0
+          exit_code=139
+          until [ $attempt -ge 3 ] || [ $exit_code -ne 139 ]; do
+            ((attempt+=1))
+            exit_code=0
+            echo "Attempt: ${attempt}/3"
+           dotnet format style --severity info --verify-no-changes --report ./style-report.json -v d || exit_code=$?
+          done
+          exit $exit_code
 
-      # For some reason this step sometimes fails with exit code 139 (segfault?),
-      # so should that be the case we'll try again (3 tries max).
+      # For some unknown reason this step sometimes fails with exit code 139 (segfault?),
+      # so in that case we'll try again (3 tries max).
       - name: Run dotnet format analyzers
         run: |
           attempt=0
